from .history_view import *
from .manage_delivery_man_view import *
from .manage_plates_view import *
from .manage_menu_view import *
from .manage_orders_view import *
from .profile_view import *
from .dashboard_view import *
from .assign_delivery_view import *
from .assign_pickup_view import *
