# Generated by Django 5.2.3 on 2025-10-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japapou', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Placa_moto',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cor_moto',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
