# Generated by Django 5.2.7 on 2025-10-13 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japapou', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_delivery',
            name='delivery_man',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario': 'DELIVERY_MAN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_entregues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='japapou.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order_delivery',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order_delivery',
            name='dispatch_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
