# Generated by Django 5.2.6 on 2025-10-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japapou', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
    ]
