# Generated by Django 5.2.3 on 2025-10-05 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japapou', '0002_customuser_placa_moto_customuser_cor_moto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Delivery',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='japapou.order')),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dispatch_date', models.DateTimeField()),
                ('delivery_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Pedido Delivery',
                'verbose_name_plural': 'Pedidos Delivery',
            },
            bases=('japapou.order',),
        ),
        migrations.CreateModel(
            name='Order_Pickup',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='japapou.order')),
                ('pickup_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Pedido Retirada',
                'verbose_name_plural': 'Pedidos Retirados',
            },
            bases=('japapou.order',),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tipo_usuario',
            field=models.CharField(blank=True, choices=[('CLIENT', 'Client'), ('DELIVERY_MAN', 'Delivery_man'), ('MANAGER', 'Manager')], default=None, max_length=20, null=True),
        ),
    ]
