# Generated by Django 4.2.7 on 2025-10-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japapou', '0002_order_delivery_delivery_man_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_pickup',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
