# Generated by Django 5.2.6 on 2025-10-09 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('japapou', '0002_customuser_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Placa_moto',
            new_name='placa_moto',
        ),
    ]
