# Generated by Django 4.2.7 on 2025-10-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japapou', '0003_alter_order_pickup_pickup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_pickup',
            name='pickup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
