# Generated by Django 5.2.3 on 2025-07-25 16:41

from django.db import migrations, models  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ("japapou", "0010_alter_period_menu"),
    ]

    operations = [
        migrations.AddField(
            model_name="plate",
            name="keywords",
            field=models.TextField(null=True),
        ),
    ]
