# Generated by Django 5.2.3 on 2025-07-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japapou', '0013_plate_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='keywords',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
